### ISSUE TITLE
JotForm Updates to Streamline Category Requests

### ISSUE THREAD

**Issue by c21hornak** [Century21Stores/SPECIAL#31]
Juan is working with Andrea's team to update the current form.
[Production-Requests-DEAD-Form-RIP-March-2017.pdf](https://github.com/Century21Stores/SPECIAL/files/863300/Production-Requests-DEAD-Form-RIP-March-2017.pdf)

**Comment by juanmriosv** [comment]
[Sheet: Categories Request 2017 - 1.0](https://docs.google.com/spreadsheets/d/1BXmU6qQkp3WOyKHL3UMtjwrOOBC8_Q0Mglyeq80-F9g/edit?usp=sharing)

**Comment by c21hornak** [comment]
@juanmriosv Did they start using this yesterday? Can I also receive the emails generated by the new requests please?

**Comment by juanmriosv** [comment]
@c21hornak 
Yes, I sent it to Alexys. She is going to send all the emails of the Merch members that will use it (still waiting for it). From our conversation with them, they supposed to start trying it this week.
New requests are being sent to webproduction@c21stores.com. I can explain why this instead of individual emails. I will send a test soon.




cc: @lstaab

**Comment by juanmriosv** [comment]
Invites Sent. Waiting for merch to setup in their end.

**Comment by c21hornak** [comment]
Juan sent "[Category Request 2017: 1.0](https://docs.google.com/spreadsheets/d/1BXmU6qQkp3WOyKHL3UMtjwrOOBC8_Q0Mglyeq80-F9g/edit?usp=sharing)" on 3/28/17.

Merchandising started using on 3/30/17.

Closing.
